### PR TITLE
Have the array radius defined just in the reaction header

### PR DESCRIPTION
**Pull request by berjones**

### CODE REVIEW

**Comment by inkdot7** [comment]
Just out of curiosity, I had a look.  When trying to rebase this [berjones:master](https://github.com/berjones/ISSSort/tree/master) on top of current master, the following remains:
```
pick da8b6dc Fix bug in energy loss and phc correction
pick ba2fb8f Turn butler algorithm back on
pick e220654 Fixed the indexing of modules for detectors from nptool
pick 665158a .
pick 68bc6da Fix module indexing of detectors from nptool
pick 0b501d2 Fix bug in energy loss and phc correction
pick 022694a .
pick d37d241 define array_radius in one place plus CFD time for simulation
pick 42df42b CFD time for simulation
```
It looks like 'Fix bug in energy loss and phc correction' appears twice.  d37d241 introduces a merge conflict marker.
Several of the commits also have DOS-style line breaks.

One way to deal with this might be to cherry-pick (groups of) individual commits on top of origin/master and provide as separate PRs.

**Comment by inkdot7** [comment]
Trying to do the rebase above, the first commit
```
da8b6dc Fix bug in energy loss and phc correction
```
has a merge conflict (which I did not try to resolve yet).

Ignoring that, a few of the other become no-ops (i.e. have presumably already been merged), and these remain after a rebase:
```
* 0bc8de8 (HEAD -> berjones_rebase, inkdot7/berjones_rebase) CFD time for simulation
* 0123d0c define array_radius in one place plus CFD time for simulation
* 0c56d14 .
* be98f85 Fix bug in energy loss and phc correction
```

Such a rebase is in https://github.com/inkdot7/ISSSort/tree/berjones_rebase , comparison: https://github.com/ISOLDESolenoidalSpectrometer/ISSSort/compare/master...inkdot7:ISSSort:berjones_rebase

**Comment by lpgaff** [comment]
I have now manually cherry-picked these changes on to my own development branch, so I will close this when I make those commits available on the main branch

**Comment by lpgaff** [comment]
resolved in #56

**Pull request closed without merging**
