### PR TITLE
Update Histogrammer.cc for array channel/gap sized bins in Ex/E_vs_z 2D histograms

### PR DESCRIPTION
**Pull request by dj-clarke**

### CODE REVIEW

**Review by lpgaff — APPROVED** [review]
I am approving this for now, but there a couple of things that could be improved.

First of all, the number of bins in the histogram definitions can be set to `zbins.size()+1`, instead of the fixed value of 517 that you currently have.

Secondly, it would be a good idea to add in a bin for the inter-wafer gaps. This could be achieved by changing line 38 to be `if( ch == 128 )`, i.e. dropping the condition on the row number. Then you would have to update line 39 to the position of the centre of the inter-wafer region, which I think would be `zbins.push_back( d + 1.508 + 0.25 );`

**Comment by lpgaff** [comment]
I've just read it in a bit more detail and you count from 0 up to and including 128, so this gives the inter-wafer gap... So it works for now, but I am guessing my suggested change would make the bin widths of those edge strips a bit more consistent. You can then change the condition that it counts from 0 up to 127...

**Comment by dj-clarke** [comment]
Ah yeah, I will change bin number definition.

I am not sure what you mean by the edge strip bin width consistency though. The bin widths of array channels are all 0.953 mm and the bin widths of inter-wafer gap are all 3.516 mm using this method.

**Comment by lpgaff** [comment]
There is also a 0.5 mm gap between the wafers. But that is included in your distance between wafers (125.5 mm), which are 125.0 mm long.

From ROOT documentation: `xbins | array of low-edges for each bin. This is an array of type float and size nbins+1`.
As far as I read this, you are correct. I assumed that we needed the bin centres, but we actually want the low edges, so the bin representing the gap, i.e. `ch==128`, has it's low edge equal to the upper edge of the last strip.

Ok then, just update the number of bins and we're done. Thanks very much for this improvement!!

**Pull request merged**
