### PR TITLE
Bug in autocal residuals plot

### PR DESCRIPTION
**Pull request by dj-clarke**
Now plotting residuals against ADC peak centroid channel rather than DetectedEnergy. Also added the full expression for effective variance of y data from https://pubs.aip.org/aapt/ajp/article/50/10/912/1051796/Least-squares-when-both-variables-have although this probably does not make a difference with tiny alpha particle energy errors.

### CODE REVIEW

**Comment by lpgaff** [comment]
Great, thanks for the update, Dan. One question about the effective variance method: do we need to manually do this for a TF1 in ROOT, or does the standard ROOT minimizer consider uncertainties in both directions? I don't know the answer to this, but if it does a standard least-squares minimisation, then we should consider propagating the uncertainty using this effective variance method, otherwise the "y-axis" value only contains the alpha energy uncertainties...

**Comment by lpgaff** [comment]
And a second question, why do want to plot against ADC value rather than energy? Is it not easier to understand the residuals plot if you have the alpha energy on the x axis?

**Comment by dj-clarke** [comment]
I believe ROOT does this by default in the fitting procedure of graphs with errors in both x and y. From https://root.cern.ch/doc/master/classTGraph.html#aa978c8ee0162e661eae795f6f3a35589, there is an option to not include x erros in the fit. I have also manually changed errors in both directions and this has altered fit values. The calculation of the effective variance is then just needed for visualistaion in the residuals plot.

I guess it comes down to preference which data is used as the x coordinate in the residuals plot. With this for me, its to zoom in and show how the fit of energy vs ADC centroid value looks, as it is difficult to make out error bars on the full plot of the fit. But then should the errors in both directions actually be shown? Suppose it does not matter so much and I should probably just write my thesis...

**Comment by lpgaff** [comment]
> Suppose it does not matter so much and I should probably just write my thesis...

Yes, you should!

Thanks for confirming that ROOT does the fit correctly, that's reassuring. I'll merge. If somebody complains that they want energy on the x-axis, we can switch it back...

**Pull request merged**
