### PR TITLE
Rx tree test

### PR DESCRIPTION
**Pull request by hanstt**
Added a tree to the histogrammer which takes some simple variables from the ISSReaction class, the tree ends up as "rxtree" in the hists output file.

### CODE REVIEW

**Comment by hanstt** [comment]
Rebased against the current master.

**Comment by inkdot7** [comment]
@lpgaff Could you review this PR?

**Comment by lpgaff** [comment]
Does #66 resolve this? Is there anything I’m missing that should be tweaked?

**Comment by lpgaff** [comment]
Implemented in PR #66

**Pull request closed without merging**
